version: '3.8'
services:
  mariadb:
    image: mariadb:10.6.4-focal
    container_name: '${APP_NAME}_db'
    environment:
      MARIADB_USER: '${MARIADB_USER}'
      MARIADB_PASSWORD: '${MARIADB_PASSWORD}'
      MARIADB_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - db_conf:/etc/mysql
    networks:
      - example-network
    ports:
      - ${MARIADB_PORT_APP}:${MARIADB_PORT_CONTAINER}
  api-service-example:
    container_name: '${APP_NAME}_app'
    build: .
    networks:
      - example-network
    ports:
      - ${APP_PORT}:${CONTAINER_PORT}
    environment:
      WAIT_HOSTS: mariadb:${MARIADB_PORT_CONTAINER}
    volumes:
      - .:/app
networks:
  example-network:
volumes:
  db_data:
  db_conf:
