version: '3.8'
services:
  mariadb:
    image: mariadb:10.6.4-focal
    container_name: '${APP_NAME}_db'
    environment:
      MARIADB_USER: '${MARIADB_USER}'
      MARIADB_PASSWORD: '${MARIADB_PASSWORD}'
      MARIADB_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - db_conf:/etc/mysql
    networks:
      - example-network
    ports:
      - 3307:3306
  api-service-example:
    container_name: '${APP_NAME}_app'
    build: .
    networks:
      - example-network
    ports:
      - 3002:3002
    environment:
      WAIT_HOSTS: mariadb:3306
    volumes:
      - .:/app
networks:
  example-network:
volumes:
  db_data:
  db_conf:
